# Generated by Django 3.1.3 on 2023-04-08 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('pclass', models.CharField(max_length=16)),
                ('pMain', models.TextField()),
                ('pSoup', models.TextField()),
                ('pSub1', models.TextField()),
                ('pSub2', models.TextField()),
                ('pSub3', models.TextField()),
                ('unitprice', models.IntegerField(default=0)),
                ('discountrate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
